doctrine:
    dbal:
#        url: '%env(resolve:DATABASE_URL)%'
        driver:   pdo_mysql
        host:     '%database_host%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Web:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Web/Entity'
                prefix: 'App\Web\Entity'
                alias: App

            App\Core:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Core/Entity'
                prefix: 'App\Core\Entity'
                alias: App