export default [
  {
    id: 1,
    title: 'Бойлерное (светлое 4,5%)',
    price: 75,
    measure: 'л',
    amountStep: 0.5,
    priceAmountStep: 1,
    category: 'beer',
    minAmount: 1,
  },
  {
    id: 2,
    title: 'Афипское (н/ф белое 4,5%)',
    price: 85,
    measure: 'л',
    amountStep: 0.5,
    priceAmountStep: 1,
    category: 'beer',
    minAmount: 1,
  },
  {
    id: 3,
    title: 'Афипское (н/ф пшеничное 4,5%)',
    price: 85,
    measure: 'л',
    amountStep: 0.5,
    priceAmountStep: 1,
    category: 'beer',
    minAmount: 1,
  },
  {
    id: 4,
    title: 'Варница (бархатное темное 4,0%)',
    price: 85,
    measure: 'л',
    amountStep: 0.5,
    priceAmountStep: 1,
    category: 'beer',
    minAmount: 1,
  },
  {
    id: 5,
    title: 'Пегас (н/ф 4,0%)',
    price: 60,
    measure: 'л',
    amountStep: 0.5,
    priceAmountStep: 1,
    category: 'beer',
    minAmount: 1,
  },
  {
    id: 6,
    title: 'Шумерское (светлое 4,5%)',
    price: 75,
    measure: 'л',
    amountStep: 0.5,
    priceAmountStep: 1,
    category: 'beer',
    minAmount: 1,
  },
  {
    id: 7,
    title: 'Ставгород (Премим светлое 4,5%)',
    price: 90,
    measure: 'л',
    amountStep: 0.5,
    priceAmountStep: 1,
    category: 'beer',
    minAmount: 1,
  },
  {
    id: 8,
    title: 'Царское (пшеничное н/ф 4,5%)',
    price: 70,
    measure: 'л',
    amountStep: 0.5,
    priceAmountStep: 1,
    category: 'beer',
    minAmount: 1,
  },
  {
    id: 9,
    title: 'Деревенское (светлое 4,2%)',
    price: 85,
    measure: 'л',
    amountStep: 0.5,
    priceAmountStep: 1,
    category: 'beer',
    minAmount: 1,
  },
  {
    id: 10,
    title: 'Лимонад "Грушевый" (0%)',
    price: 40,
    measure: 'л',
    amountStep: 0.5,
    priceAmountStep: 1,
    category: 'beer',
    minAmount: 1,
  },
  {
    id: 11,
    title: 'Арахис "Тайский перец"',
    price: 460,
    measure: 'кг',
    amountStep: 0.05,
    priceAmountStep: 1,
    category: 'snack',
    minAmount: 0.05,
  },
  {
    id: 12,
    title: 'Арахис в глазури "Устрица"',
    price: 400,
    measure: 'кг',
    amountStep: 0.05,
    priceAmountStep: 1,
    category: 'snack',
    minAmount: 0.05,
  },
  {
    id: 13,
    title: 'Фисташки соленые',
    price: 1350,
    measure: 'кг',
    amountStep: 0.05,
    priceAmountStep: 1,
    category: 'snack',
    minAmount: 0.05,
  },
  {
    id: 14,
    title: 'Арахис с солью',
    price: 460,
    measure: 'кг',
    amountStep: 0.05,
    priceAmountStep: 1,
    category: 'snack',
    minAmount: 0.05,
  },
  {
    id: 15,
    title: 'Арахис "Холодец и хрен"',
    price: 460,
    measure: 'кг',
    amountStep: 0.05,
    priceAmountStep: 1,
    category: 'snack',
    minAmount: 0.05,
  },
  {
    id: 16,
    title: 'Арахис в глазури "4 сыра"',
    price: 400,
    measure: 'кг',
    amountStep: 0.05,
    priceAmountStep: 1,
    category: 'snack',
    minAmount: 0.05,
  },
  {
    id: 17,
    title: 'Арахис "Мясо на углях"',
    price: 460,
    measure: 'кг',
    amountStep: 0.05,
    priceAmountStep: 1,
    category: 'snack',
    minAmount: 0.05,
  },
  {
    id: 18,
    title: 'Арахис в глазури "Шашлык"',
    price: 400,
    measure: 'кг',
    amountStep: 0.05,
    priceAmountStep: 1,
    category: 'snack',
    minAmount: 0.05,
  },
  {
    id: 19,
    title: 'Арахис "Мексиканский"',
    price: 460,
    measure: 'кг',
    amountStep: 0.05,
    priceAmountStep: 1,
    category: 'snack',
    minAmount: 0.05,
  },
  {
    id: 20,
    title: 'Арахис в глазури "Сметана и зелень"',
    price: 400,
    measure: 'кг',
    amountStep: 0.05,
    priceAmountStep: 1,
    category: 'snack',
    minAmount: 0.05,
  },
  {
    id: 21,
    title: 'Арахис в глазури "Микс"',
    price: 400,
    measure: 'кг',
    amountStep: 0.05,
    priceAmountStep: 1,
    category: 'snack',
    minAmount: 0.05,
  },
  {
    id: 22,
    title: 'Фитсашки с перцем',
    price: 1400,
    measure: 'кг',
    amountStep: 0.05,
    priceAmountStep: 1,
    category: 'snack',
    minAmount: 0.05,
  },
];
